services:
  bot:
    build: .
    env_file:
      - .env
    restart: always
    links:
      - postgres
    stop_signal: SIGINT
  postgres:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_PASSWORD=randompassword
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - './db:/var/lib/postgresql/data/pgdata'
